### ISSUE TITLE
REST implementation still refers to property-ref and Selection Criteria entity rather than SEL codelist

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#111]
R02D02.1 in the REST Response - should this now be a value from the SEL codelist rather than a URL reference to an E11 (sic - should be E12) entity?

Also Q02D02.1 in the REST request the URI Query parameter still talks of {property-ref}

Also is E12 (Selection Criteria) deprecated in favour of SEL codelist?

**Comment by mdovey** [comment]
I assume that ../loans/items/manifestation-id=9780123456789 is a slight of the keyboard for ../loans/items?manifestation-id=9780123456789

I was assuming that in the case of 

../loans/manifestation-id=9780123456789

this would always return an empty list, since no loan can have a manifestation-id of 9780123456789 by virtue of loan not having this property.

For LCF 1.0.1 semantics this does make SEL01 - SEL04 redundant.

One use of SEL01 - SEL04 might be when we want to filter on multiple manifestation-id. In issue #85 we discuss two possible ways:

/items?manifestation-id=9780123456789&manifestation-id=9780987654321

or

/items?manifestation-id={9780123456789,9780987654321}

My preference is still the latter, as the former means different semantics for & depending on whether an element is repeated i.e.

/items?manifestation-id=9780123456789&manifestation-id=9780987654321&location-id=here

would need to be interpreted as 

(manifestation-id=9780123456789 OR manifestation-id=9780987654321) AND location-id=here

However, another option here might be regular expressions.

In terms of being able to refer to properties in parent child relationships trying to do this within the URL is messy:

/loans/items?manifestation-id=9780123456789

is unattractive as you'd expect (given other URL forms) to get back a list of items not loans. Whereas

/items/loans?manifestation-id=9780123456789

suggests that the manifestation-id is a property of loan, and

/items?manifestation-id=9780123456789/loans

whilst more human readable would trip up most URL parsers.

If we really wanted to do this, it might be better to drop the current SEL approach and go for a query language (perhaps based on xpath or xquery) which could be passed as a single query.

To move forward. I would suggest we keep the current SEL table in 1.0.1, accepting that SEL01 - SEL04 are effectively duplicating existing functionality. We also modify R02D02.1 to be selection-criteria (SEL) rather than property-ref (E12). We also deprecate E12 (would E12 be used in preference to SEL even for non-REST implementations?) 

In 1.0.2 we consider how to handle ranges, lists, and possibly regular expressions

Beyond, 1.0.2, if the use case for child\parent emerges we consider moving to a more powerful query language.

**Comment by franciscave** [comment]
Yes, I meant to type ? instead of / in several places.

I agree that we need to re-think how to express queries that are to return lists of entities, and this would probably be better done using a query language (e.g. xpath, xquery) rather than by using E12 Selection Criterion, which was probably added too hastily to LCF v1.0. I therefore agree to the proposal that we deprecate the use of E12 in LCF v1.0.1 and that we re-define R02D02.1 to be a selection criterion code value from list SEL and simply remove R02D02.3 (which was provisionally added to LCF v1.0.1).

I have made the necessary documentation changes. In the REST Web Service specification I have renamed R02D02.1 in the response to be 'code', which I think is clear, and I've made some consequential adjustments to line 6 of the request (Q02C02). 

I have left code list SEL as it is, accepting that SEL01 - SEL04 are possibly redundant. I'm happy for these to be omitted from the XML schema, in which case I can add a note that they are not included in the XML binding, if we think that is safest for now.

**Comment by franciscave** [comment]
I'd suggest that the issue of possible query language support for retrieving lists of entities based upon more complex search criteria should be a new issue, with #85 merged in with the new issue.

**Comment by mdovey** [comment]
I've created #113 to pull together the query language.

I'd also suggest modifying the ENT code list so that the note for properties reads "Deprecated in 1.0.1" rather than "Added in 1.0.1"

**Comment by mdovey** [comment]
Schema updates are ready but I want to rebase them onto master after pull request #114
