### ISSUE TITLE
Who/what creates the identifier of an entity instance?

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#18]
When an entity item, e.g. a new manifestation, is created by a request, should the identifier be excluded from the request? At present the identifier is a mandatory element for all entity items, but I think that maybe the one occasion on which it should be possible for the LMS to ignore it is when the function is 'create' and the LMS assigns the identifier.

If I'm right, I think we can address this point by extending Note [4] in the main LCF spec to explain that entity identifiers are mandatory in responses, and are mandatory in requests except when creating a new entity, in which case the LMS may ignore the identifier if included in the request.

**Comment by franciscave** [comment]
An alternative would be to explain in the note that entity identifiers are always mandatory, but that when they are included in requests to create a new entity they may be ignored by the server.

**Comment by colinparkeruk** [comment]
Conversely, for the recent sample application for the PlugFest, the identifier was optional when creating a patron. The idea was that this would cater for the situation where new barcoded borrower cards were available at the kiosk and also for when they were not (and the kiosk could then print a receipt containing a barcode to be used temporarily).

**Comment by anthonywhitford** [comment]
I think the patron and item entities are exceptional cases. Things like
loans and reservations have identifier elements, but I don't think there is
the perception that anything other than the LMS would allocate these. They
are therefore internal unique identifiers defined by the lms. For
consistency we could state this is the case for all identifier elements,
and if there is something like a barcode needed, this could go in a
different element perhaps with a type qualifier since academic libraries
sometimes use the student number as a logical identifier instead of a
barcode. Eg institutional-identifier.

**Comment by franciscave** [comment]
Have we resolved this by my addition of Note [4] in the LCF v1.0.1 spec? If so, I shall add this Note to the XML entity binding spec and we can modify the schemas to make the identifier element non-mandatory (so that it can be used to validate the payload when creating a new entity).

**Comment by franciscave** [comment]
At the Technical Panel meeting on 28 June it was agreed that the changes are satisfactory. The XML schema should be changed to allow the identifier to be omitted when creating a new instance of the entity.

**Comment by anthonywhitford** [comment]
The above amendment to the entities with the "identifier" element has been made under issue 20.
