### ISSUE TITLE
Suggestion to reserve -ref suffix for the names of elements which contain a REST url reference to a LCF entity

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#29]
I think the following XML elements are meant to contain a (locally defined) LMS identifier:

transaction-ref in the payment entity
pickup-institution-ref in the reservation entity
pickup-location-ref in the reservation entity

Although the last one might be meant to refer to a location entity?

I would recommend that these elements are renamed so that the suffix -ref is only used for elements which contain a LCF actionable URL which resolves to a LCF entity

**Comment by mdovey** [comment]
I think the same also applies to return-location-ref in the lcf-checkin-response (or is this a reference to a location entity?)

**Comment by franciscave** [comment]
I believe that the intention was that E06D07, E06D08 and R12D04 (pickup-institution-ref, pickup-location-ref and return-location-ref) would be refer to identified location entities. If in practice this is not the case, I agree that it would be better to change to names to avoid that expectation.

transaction-ref is not referring to an entity in the LCF sense, because we don't have an entity type 'transactions'. This is providing a reference that can be tied up with a specific EPOS record, which may be in an entirely separate system.

Difficult to suggest an alternative suffix, so perhaps simply drop the suffix, i.e. 'transaction'?

**Comment by mdovey** [comment]
Re - E06D07, E06D08 and R12D04

Initially I thought that E06D07 and E06D08 were references to E04 entities. However, I then looked at the main LCF document where these are described as "The LMS identifier of the branch library or other sit" which makes it sound as if this is an LMS defined identifier rather than an LCF one.

I don't know enough about the original dicussions\use case for this one to comment which it should be, but it should be one or the other (rather than undefined) and clarified.

**Comment by franciscave** [comment]
Well, identifiers are generally assigned by the LMS, as I understand it. The phrase "LMS identifier" would perhaps be clearer if it said "LMS-assigned identifier". I definitely recall that the expectation was that branches and locations within branches would be among the locations for which entities would be defined.

**Comment by mdovey** [comment]
No, to me both "LMS-assigned identifier" and "LMS identifier", imply that the string value of E06D07 (and E06D08) is the LMS-assigned identifier, whereas what I think you want is the E06D07 (and E06D08) contains a reference to an E04 entity (which would have the LMS-assigned identifier as the string value of E04D01)

**Comment by franciscave** [comment]
I think others who perhaps remember earlier discussion (Colin?) are going to have to comment on this. Each entity has an identifier by which it can be referred to. This is as true of location entities as of any other entity. The element E04D01 has the following description: "The primary LMS identifier normally used when referring to this location". This description is consistent with the wording of identifier elements for other entities. If the LMS assigns identifiers to the locations themselves, these are stored in element E04C02 Additional identifier, in which case the identification scheme is specified in E04D02.1 using code list LOI and the actual identifier is specified in E04D02.3. If the identification scheme is proprietary, the name of the proprietary scheme is specified in E04D02.2.

**Comment by franciscave** [comment]
I think I agree that the error is in the description of E06D07 and E06D08. They probably should be referring to the entity identifiers for the specific locations. However, there perhaps needs to be a discussion as to whether in practice an LMS is going to define entities for all the relevant locations or there should be a simple way to refer to a location by an identifier in some specified scheme.

**Comment by anthonywhitford** [comment]
Hi Both, 
Locations must indeed have their identifiers assigned by the LMS. A location would be something like a library branch or similar, which is specific to a single library service. Library location codes/identifiers therefore cannot be assigned by anything other than the LMS, since the data required for a library would be so diverse and different. 

I also expect that all <identifer> elements are assigned by the LMS, since as Francis mentioned, they are the identifiers used within the LMS to refer to the entity. There are two entities where this does not hold true at the moment, Patron and Item, since the <identifier> element for these is currently described as the barcode. I think this should change, but that's not for this issue. 

In practice, there should be at least one row in a table in a database representing a library location. I think that holds irrespective of which LMS you're talking about. Without that, there would be no mechanism to infer integrity within the data of the LMS, or choose which location you wanted from any selection process within the existing LMS user interface. 

I don't think there is any need to add in the word "assigned" to the lms identifier talked about above.

**Comment by mdovey** [comment]
Sorry, I think you are missing my original point which was about the pickup-institution and pickup-location in the reservation entity, and clarifying in the documentation whether these are meant to be URL references to locations or an abitrary string identifying the institution\location.

The note against these currently reads that these contain an "LMS identifier" which I would interpret as meaning the latter. If these are (as I think they are meant to be), I would suggest that the text states that these contain a reference to a location (and any mention of LMS identifier occurs in the notes for the location entity).

**Comment by franciscave** [comment]
I think I agree that the descriptions of E06D07 and E06D08 should be changed to make it clear that these are references to location entities, with some additional wording to convey the intention that in each case what kind of location is expected. In fact, we can probably specify that E06D07 MUST refer to a location entity with location type '01' (code LOT01). I think that E06D08 can refer to a location entity of any of the location types in code list LOT, but if E06D07 is included one would expect E06D08 to refer to a location of type '02' or '03'.

However, does this discussion suggest that we don't have a consensus as to the meaning of the term "LMS identifier"? If so, we will have to review the use of this term in the description of all entity identifiers E01D01 through E11D01. (In passing I note that E09D01 doesn't have a description and E11D01 actually is described as a "system identifier", so there's definitely some tidying up still to do...)

**Comment by mdovey** [comment]
I think we all generally agree what an LMS identifier is - namely a string whose value is determined by the LMS implementation. 

There is a second issue, however, about what strings we use in the identifier fields of LCF entities. Should the values be purely determined by the LCF implementation or determined from elsewhere, e.g. an alternative structure for location (sticking with a XML representation) might be

<location>
  <identifier>LCF generated id</identifier>
  <LMSIdentifier>identifier of the location from the LMS</LMSIdentifier>
...
</location>

rather than overloading a single identifier field as at present (likewise for other entities) - see issue#20

**Comment by mdovey** [comment]
As E01D16 is not a reference to a LCF URI but rather an LMS URI, I'm in two minds about having this use the suffix -ref. My view would be for -ref to be only used for LCF URIs and perhaps rename this manifestation-record-uri

E01D06.3 should this be just the id of the related manifestation or a full URI?

**Comment by franciscave** [comment]
Good point about E01D16. But would it necessarily be a URI? Yes, it would in the case of a RESTful web service implementation. I suppose one could argue that one could express or more less any kind of query as a URI. An alternative might be manifestation-record-link or manifestation-record-href, but I'm not particularly enchanted with either of these.

E01D06.3 should end in -ref, since it's supposed to point to another manifestation entity. Good catch. other-manifestation-in-series-ref is a bit cumbersome, but it has the virtue of being self-explanatory.

**Comment by franciscave** [comment]
I've adjusted the description of entity identifier elements so that it is made clear that these are LCF entity identifiers and not some other kind of identifier. I've re-named <other-manifestation-in-series-id> to <other-manifestation-in-series-ref>. I've looked for uses of the term 'LMS identifier' and changed these to 'LCF entity identifier' where appropriate, including in E06D07 and E06D08.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. The technical editors need to update the XML schema to be consistent with the documentation changes.

**Comment by mdovey** [comment]
Looking through this, I don't think we resolved E08D10 (transaction-ref) which is an LMS identifier\reference for the transaction not a reference to an LCF entity

I would suggest maybe renaming this to transaction-reference unless there's a better solution?

**Comment by mdovey** [comment]
Also what was the conclusion about renaming E01D16 (manifestation-record-ref) as this is a URI or link to a LMS record (precise format defined by the LMS) not a reference to an LCF entity?

**Comment by franciscave** [comment]
How about `manifestation-record` for E01D16, and `transaction-reference` for E08D10?
