### ISSUE TITLE
Why is loan-status within the loan entity repeatable

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#30]
Why is the loan-status field within the loan entity repeatable. Surely only one status can be applicable at any one time?

**Comment by franciscave** [comment]
If you look at code list LOS, several of these could apply to a single loan, or so I believe. We could of course change the data type to a space-separated list of code values. I'm not terribly keen on that, because one needs to parse the list as well as the XML, although I know this is easy enough to specify in XSD.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. It was agreed that a loan might have several statuses simultaneously, e.g. '01' (On loan to patron) and '04' (Charge owed). It was agreed that no change to LCF is needed.

**Comment by anthonywhitford** [comment]
No change required, closing.
