### ISSUE TITLE
Need a security-resensitize field in lcf-checkin-response

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#31]
lcf-checkout-respnse has a security-desensitize field to instruct a self issue kiosk to disable any security tag.

Shouldn't lcf-checkin-response have a corresponding security-resensitize field to instruct the kiosk to re-enable the security tag?

**Comment by franciscave** [comment]
I vaguely remember some discussion from way back about this. I think that it was thought that the purpose of this was to ensure that the security tag was removed or de-sensitized before the item was taken out of the library, but that the same kind of reminder wasn't needed on check-in because it would fall within the normal protocol for handling items that have been checked in before they get put back on the shelf.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. All items are, by default, re-sensitized on check-in. Items that must not be re-sensitized, e.g. because they contain magnetic media, are flagged in the item record by E02D07 media-warning. It was agreed that no change to LCF is needed.

**Comment by anthonywhitford** [comment]
No change required, closing.
