### ISSUE TITLE
Purpose and content of lcf-reservation-response

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#32]
Why does lcf-reservation-response apparently contain both a reference to the reservation entity record and also a copy of the reservation entity record?

For that matter, it isn't clear what additional information is in the lcf-reservation-response which isn't already in the reservation entity (i.e. what purpose is serve by returning lcf-reservation-response over just returning the reservation entity?)

**Comment by franciscave** [comment]
The element R16D01 and R16C02 (R16D02 is an error in the spec) are intended to be mutually exclusive. Either the response contains a reference to the reservation or it contains the reservation entity. If there are charges associated with the reservation and the reservation entity itself is not returned in the response, references to any associated charges should be included in the response, to alert the user to the charges, which they might otherwise miss if they don't choose to retrieve the full reservation entity.

I think there was a business case for not returning the full reservation entity, but I confess that I no longer remember what it was. It may be that we can drop from the REST Web Server the option of returning a reservation reference, in which case the optional charge references in the response can also be dropped.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 28 June. After some discussion it was agreed that, for the web service implementation at least, it is only ever necessary to return a reservation reference URI in the reservation response. The documentation and XML schema should therefore be changed to remove the option of including the whole reservation record in the response.

**Comment by anthonywhitford** [comment]
Having reviewed the comments above, I think @mdovey has a valid point that there is no purpose in the entity "lcf-reservation-response". Returning the reservation entity answers all the questions, and the LMS/ILS should have all the required information since it has just completed creating the reservation. 

The one caveat on this statement is what should be returned if the busniess rules deny the creation of the reservation? The current LCF spec states that the lcf-exception entity should be returned along with the appropriate HTTP response code.

Given these two scenarios of use, I think the existing lcf-reservation-response should be removed.

**Comment by franciscave** [comment]
I agree. I have edited circulation function 16 in the LCF 1.0.1 REST Web Services Specification to reflect this decision. The specification now says that the only response to a reservation request should be either an HTTP 201 response (if successful) or an LCF Exception Response (if not successful).
