### ISSUE TITLE
Various enumeration issues in xml schema

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#38]
The following I presume are just errors in the xml schema enumerations and I'll just fix unless anyone shout:

circulation-status goes up to 13 in xml schema but 16 in the code list
charge-type goes up to to 10 in xml schema but 13 in code list

However, slightly less obvious:

charge-status goes up to 04 in the xml schema but only 01, 02 and 03 are defined in the code list, is this an error in the schema or is there a 04 which hasn't been added to the code list?

**Comment by franciscave** [comment]
Regarding circulation-status and charge-type, yes, these are errors, caused by the schema not being updated when extra codes not supported by SIP2 were added to the LCF code lists CHT and CIS. Mea culpa!

Regarding charge-type, this is a similar error, but in this case a code value '04' meaning 'Waived' (Cancelled but left on record) was removed from code list CHT when code values '08' (Forgiven) and '09' (Waived) were added to code list PYT (Payment Type).

**Comment by mdovey** [comment]
Updated enumerations - commit  d18d7d1
