### ISSUE TITLE
Retrieve the ISBN associated with an Item

### ISSUE THREAD

**Issue by colinparkeruk** [anthonywhitford/bic-lcf#4]
Would it be reasonable for the ISBN to be returned in the E02C02 Additional identifier field of an Item record or would an additional call to retrieve the Manifestation record be required?

**Comment by franciscave** [comment]
An Item is an specific copy of a Manifestation. It is the Manifestation that has the ISBN, so you'd need to retrieve the Manifestation record to retrieve the ISBN. Two Items couldn't share the same identifier, because identifiers are supposed to be unique, so we couldn't add ISBN to code list IMI as an alternative identifier type for an Item.

**Comment by colinparkeruk** [comment]
Understood. In hindsight, the ISBN may be derivable from the E02D03 Manifestation reference.
