### ISSUE TITLE
How can I make a credit payment against a Patron?

### ISSUE THREAD

**Issue by anthonywhitford** [anthonywhitford/bic-lcf#57]
Discussed in the LCF Review Panel Meeting 2017-03-22.

Westmister have the wish to remove cash handling from their libraries. We discussed whether this would be a good reference implementation for LCF, however we need to ensure that the following are possible:

Scenarios:
- [ ] Authenticate an end user terminal ensuring they have permission to access Patron Charges
- [ ] Authenticate an end user terminal ensuring they have permission to apply new Patron Charges
- [ ] Find a Patron
- [ ] Add a charge to a Patron
- [ ] List charges against a Patron
- [ ] Pay a single charge against a Patron using new money
- [ ] Pay a single charge against a Patron using money already on account
- [ ] Pay multiple charges against a Patron using new money
- [ ] Pay multiple charges against a Patron using money already on account

**Comment by franciscave** [comment]
In addition to the above, we need to enable a Patron to put money on account, so that there are funds available for payment future charges using money already on account. We already have circulation management function 13 Patron payment, but there is not currently a way of making a payment simply to credit an account. The assumption is that a payment is made to clear one or more charges. See the description of Q13D03 Charge reference, where it says: "If [charge reference is] omitted, the LMS determines the charges against which to set the payment.". A simple option would be to extend this sentence with the words "and, if no charge is due, the LMS credits the Patron account with the paid amount". This would imply that a payment is always used to clear charges, if any are due, and only if there are no charges due would they be used to add credit to an account. Is this what happens in practice? Could a Patron choose to add credit to an account without first clearing all charges currently due?

**Comment by franciscave** [comment]
LCF v1.0.1 and XML binding documentation updated to make E08D05 (charge reference) non-mandatory in payments, for payments (credits) that are applied to an account without reference to any charges.
