### ISSUE TITLE
Add Notification mechanism

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#59]
Add a mechanism for notification\alerts to patrons.

**Comment by colinparkeruk** [comment]
I suggest that a patron message feature should be catered for by LCF. 
The message entity would include an 'audience' field to specify whether the message is for a patron or about a patron (and only visible by staff).
The message entity would include an 'acknowledged' flag to allow the audience to note that it has been read and suppress a possible 'unread messages' alert.

**Comment by franciscave** [comment]
We agreed during the Panel meeting on 31 January that a new Message entity is required, to enable messages and alerts of various kinds to be sent to Patrons. I would propose that such an entity should have the following properties:
- message/alert identifier
- message institution reference (reference to the Institution entity responsible for the message, if needed)
- message/alert type (code value from a new code list MAT)
- message/alert display type (code value from existing code list MGT)
- message/alert display from date/time (only included if the same for entire audience)
- message/alert display to date/time (only included if the same for entire audience)
- message/alert audience (code value from new code list MAU)
- patron reference (only used if the audience code indicates 'patron list') - repeatable
- message/alert text (composite)
-- message/alert text format (code value from new code list TFT)
-- message/alert text string

**Comment by franciscave** [comment]
The new code lists could be:

MAT Message/alert type
01 = Action required
02 = Institution information (e.g. opening hours, closures, etc)
03 = Acquisitions and disposals, other collection information

MAP Message/alert priority
01 = High
02 = Medium
03 = Low

MAU Message/alert audience
01 = All patrons
02 = Patron category
03 = Patron list

TFT Text format
01 = Plain text
02 = HTML text
03 = Proprietary

**Comment by franciscave** [comment]
Some messages/alerts may be used repeatably with different patrons and different times, in which case display from and to fields would not be included in the message, but would be added to the patron records. I envisage that we would need to add a message reference composite to the Patron entity, e.g.

E03Cnn Message/alert (0-n)
E03Dnn.1 Message/alert reference (1)
E03Dnn.2 Message display from date/time (0-1)
E03Dnn.3 Message display to date/time (0-1)

For example, there might be a general message to alert patrons about overdue items on loan. The message type would be 'action required', the priority would be 'high' and the audience would be 'patron category', which would contain a library-specific category code for 'patrons associated with overdue loans'. When a loan is overdue, the patron record would be updated to include a reference to this message. It would not be necessary to specify display from/to date/times, because the message would be displayed indefinitely whenever a patron record containing a reference to this message is retrieved.

**Comment by franciscave** [comment]
This has now been implemented. I've added entity E15 Message/alert to the LCF v1.0.1 specification and entity XML binding, and I've created code lists MAP, MAT, MAU and TFT. I've made the message/alert text composite repeatable, to cater for situations where the same message/alert might be available in different text formats. I have not yet added the message/alert refererence to the Patron entity.

**Comment by franciscave** [comment]
This was reviewed by the Technical Panel earlier today. Further documentation changes are required to support messages that are only to be displayed until the Patron has acknowledged that they have read the message.

**Comment by franciscave** [comment]
I've added E03C34 Associated message/alert to the Patron entity, to allow a Patron record to carry references to the messages/alerts that they have or have not yet read. This contains: E03D34.1 Message/alert reference, linking to a specific Message/alert record; and E03D34.2 Message delivery status, containing a delivery status code from new code list MAD. When a Message/alert is created/activated, a reference to it would be added to the record of every relevant Patron. When a Patron logs in at a terminal, the server would check the Patron record for any associated Messages/alerts that have not yet been delivered and whether or not acknowledged in order to determine which Messages/alerts to display. The relevant Message/alert records can then be retrieved for display purposes.

I have also modified the Message/alert entity (E15) to include Message/alert display/delivery constraint, using new code list MAC to indicate whether to display the message between certain dates, until acknowledged, or not to display it (for inactive messages that may be activated in future).

**Comment by franciscave** [comment]
At today's Subgroup meeting I realised that I hadn't documented the new function 32 'Acknowledge message/alert'. We agreed that this is needed so that, as in online banking, a Patron can actively confirm that they have read a particular message. I have modified the LCF v1.0.1 specification to include function 32 as a specialisation of function 04 (Modify entity item). However, I'm not sure how best to implement this in the REST Web Service specification. Using HTTP PUT would seem to me to be overkill, when only one small change to the Patron record is required. I'm wondering about using HTTP PATCH, but I'm not sure whether this would be a popular choice in REST circles. Any thoughts?

**Comment by mdovey** [comment]
The XML Schema documentation for E15 (Message \ Alert) seems to be missing element E15C12 ( Message/alert text )

**Comment by mdovey** [comment]
For the REST webservice, I'm not entirely sure what happens if you use TFT01, TFT02 or TFT03 is the plain text encoding does not match the encoding specified in the xml declaration

**Comment by franciscave** [comment]
Changed MAD to MAC in the code list heading.

Added E14C12 to the XML binding specification.

Hmm... good question about encodings. Do you think it would be safest just to have one code value for 'plain text' and say that the encoding of the message text must match the encoding of the XML payload? The only way I can think of for mixing encodings would be to base64-encode the message text if its encoding doesn't match that of the payload.

**Comment by mdovey** [comment]
I think I would go for a single plain text code value.

Even if LCF were using a different presentation format (e.g. JSON), we would still need to have agreed (out of band) what text encoding was being used for the payload itself and/or all strings within the payload before transmitting the payload, and so we can assume that plaintext in this field is in the same encoding as every other string field.

**Comment by franciscave** [comment]
OK, I've added TFT08 with code value '04' to the code list, for specifying plain text where the encoding is specified at the message level. I can adjust the wording further if this isn't clear. I decided to leave TFT01, TFT02 and TFT03 untouched. Please add TFT08 to the schema in place of TFT01, TFT02 and TFT03, which should be excluded.
