### ISSUE TITLE
Two phased transaction process for payment

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#60]
There may be a problem with payment processors whereby a transaction cannot be reversed if the LCF server refuses the payment (e.g. if the payment will take the account into credit but the LMS does not support accounts being in credit).

One solution would be to modify the payment process to be "2 phased". The workflow would be

a) device sends a notification of the intended payment
b) LCF service accepts the notification (proceed to c) or rejects the notification (abort)
c) device takes payment via payment processing system
d) device informs the LCF service that payment has been successful or payment has failed.

**Comment by andrewdaye** [comment]
Has there been any discussion of a more generic "try before commit" paradigm for the POST or PUT-type calls? For example, the client effectively makes the call with a flag that they don't want to commit to the transaction, just to "check" if it will proceed successfully. This would fit with parts (a) and (b) above for payments, but could also work across other calls - e.g. can I create a reservation for this item? , can I create this Loan? These "try before commit" calls could also provide a way of informing the client (borrower) of any cost involved in the transaction.

**Comment by franciscave** [comment]
I don't recall any discussion of the "try before commit" paradigm, but I like the idea of a general solution of this kind. So far as LCF is concerned, making a payment simply involves the creation of a Payment entity item (i.e. record) (function 13), which is essentially the same as creating any new entity item (function 03). I presume that HTTP provides some mechanism for the server to give a provisional response, to be confirmed by a further response once creation of the new record has succeeded. In the case of making a payment, if the LMS doesn't allow accounts to go into credit, attempting to create a Payment record for an amount that would take the account into credit would simply fail before the payment transaction proceeded. Otherwise, creation of a new Payment record would only have succeeded once the payment transaction was completed successfully.

**Comment by mdovey** [comment]
HTTP\Rest does not have an explicit two phase commit mechanism. The closest are HTTP response codes 100 (Continue) and 202 (Accepted). Neither quite meet the two phase commit requirements:

100 (Continue) - allows the client to send the HTTP headers only - the server can either reject (via a suitable error http response code) the headers, or indicate that the client should send the body via the 100 response. In a two phase commit, we need to send both headers and body, and for the server to indicate whether it would accept them.

202 (Accepted) - this allows an asynchronous operation. The message has been accepted but will be processed as some future date. Whilst the description includes the instruction that the response " SHOULD include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled" - the assumption is that this is human readable rather than machine readable. Also whether to use this response is server determined rather than requested by the client.

Possible solution:

i) a bespoke header (transaction-start=true) to initiative a transaction
ii) server either rejects the request (with appropriate response), or accepts using the 202 response code. The response includes the headers transaction-id which the client must use to commit the transaction in a future response, and transaction-expires which gives a date time stamp in ISO format. The server makes a commitment to accept the request without error until the transaction-expires time. No guarantees on behaviour are made after this time.
iii) client may then send the request again with either
transaction-commit=id to confirm the request or transaction-abort=id to explicitly cancel the request (the alternative of allowing the transaction to expire will result in unnecessary state management on the server).

**Comment by mdovey** [comment]
Given the potential heavy weight solutions needed for two phased commit (which is an uneasy fit with the REST metholology), the LCF review panel on the 4/7/2017 expressed concern whether this was a real issue or hypothetical one. 

Issue downgraded to low priority pending use cases or arguments for this requirement from vendors and implementors

**Comment by colinparkeruk** [comment]
SIP2 included the 'fee acknowledged' flag in the Checkout, Hold, Renew and Renew All functions to allow a patron to cancel a request if they objected to the charge that would be incurred. Admittedly, this could be implemented by simply reversing the transaction but that may be trickier to implement for the LMS.

SIP2 didn't include the flag in the Fee Paid message, maybe because it was in the days before credit cards.

bibliotheca have been involved in implementations where the payment provider does not include a function to reverse or cancel a card transaction. If a two-stage LMS transaction is not feasible then maybe a means of reversing the original creation of the Payment entity would be an alternative solution.

**Comment by franciscave** [comment]
LCF has a 'charge acknowledged' flag, which is equivalent to the SIP2 'fee acknowledged' flag (SIP ID 'BO'). This can occur on checkout / renewal (element Q11D07) and reservation (element Q16D10). That simply is the way that the borrower acknowledges that they're going to have to pay a fee.

**Comment by colinparkeruk** [comment]
I believe that the two-phased payment process, as described initially above, can be implemented in the same way as an item checkout is, where the 'charge acknowledged' flag is utilised.

If I have understood the meaning of the 'confirmation' flag, e.g. Q11D01, this would meet the requirement cited by Andrew above for checkout/renewal and reserve. If this flag was included for Patron payment, it would allow for a two-phased process.

**Comment by franciscave** [comment]
If I understand this correctly, what we're saying is that there would be a request to accept payment on given terms (amount, payment method and charges against which the payment is to be off-set). If (and only if) this request is accepted would the financial transaction proceed. If the transaction is successful, e.g. the patron's bank or credit card company authorises the transaction, a confirmation payment request is immediately sent, which cannot be rejected by the LMS and which applies the payment to the patron's account on the agreed terms. In which case all we need to do is add an extra value to code list RQT (the meaning of '04' could be extended, but probably cleaner to add a new code value) and add an extra element Q13D06 Payment confirmed.

**Comment by franciscave** [comment]
Actually, maybe two new elements are needed: one containing the authorisation from the LMS to go ahead with payment on the specified terms (i.e. an authorisation reference - entity E11?) and another containing a transaction reference to include when the LMS creates a new payment entity (E08). In which case R13 needs a new element to contain an authorisation reference.

**Comment by colinparkeruk** [comment]
I believe that Francis' solution meets the requirement for a two-phase payment request. I also believe that a Use Case is no longer required for this issue since it has been described above.

**Comment by franciscave** [comment]
In the code lists added code AUT02 with value 'PAY' for authorisations of payments. Added code RQT05 with value '05' for confirmation requests following a successful payment transaction. 

In the LCF Version 1.0.1 specification added R13D04 Authorisation reference, giving authorisation for a Patron to proceed with the payment transaction; and added Q13D08 Transaction reference, providing the transaction reference to the LMS when confirming a successful payment transaction.

**Comment by franciscave** [comment]
Having completed the documentation changes, I'm not entirely convinced that the additional request type code RQT05 is actually needed, but it might be in non-RESTful implementations of LCF, so I feel inclined to leave it in.

**Comment by franciscave** [comment]
At today's Subgroup meeting it was agreed to implement this as currently specified. We can review later whether RQT05 is actually needed or not.

**Comment by mdovey** [comment]
RQT Request type is not used in the web service implementation. There are alternatives to some of these request types (e.g. confirmation via a URL query parameter, cancellation via a DELETE http operation). However, I'm not sure how to do other request types (e.g. quotation request), and in particular, how a confirmation request is set.

**Comment by franciscave** [comment]
The web service implementation of function 31 (as with functions 11 and 16) includes a 'confirmation' parameter. If '?confirmation=Y is added to the request URI, this is equivalent to RQT02 or RQT05. This is documented in the LCF 1.0.1 REST Web Service specification.

**Comment by mdovey** [comment]
It might be lack of knowledge of the purpose of RQT02, however if '?confirmation=Y' corresponds to both RQT02 and RQT05 then what is the difference between RQT02 and RQT05 (i.e. why aren't we just using RQT02 for two phased commit).

Also, how is RQT04 (quotation request) done in via REST?

**Comment by franciscave** [comment]
For some reason I thought that a specific code would be needed for confirming a payment following a successful transaction, but I cannot now explain why I thought this. I think we should drop RQT05 from LCF v1.0.1. I will remove it from the specifications.

As for RQT04, this has not yet been implemented in REST. In retrospect, it was possibly a mistake to specify a query parameter 'confirmation', because 'request-type' might be better: when included, this could take a value '02' or '04'. But I'm not sure that the POST method is appropriate in the case of a quotation. I don't immediately see a simple resolution of this issue. This will need more thought and discussion, so I suggest that we raise this as a separate issue and discuss it for a future revision of the REST specification.

**Comment by mdovey** [comment]
I've added issue #84 to take forward RQT04, this might involve rethinking the "confirmation" query parameter
