### ISSUE TITLE
Deprecate use of HTTP Response Code 207

### ISSUE THREAD

**Issue by mdovey** [anthonywhitford/bic-lcf#65]
This was discussed in e-mail in Jan 2016 but not acted upon.

The current documentation states that "If the request is unsuccessful, the HTTP response will include an appropriate status code, which may be 207 (Multi-status), in which case the response must contain an XML payload that conforms to the LCF exception conditions XML schema."

Both Anthony and I felt that this was a misuse of 207 which only really makes sense witihn the cotext of [WebDAV](https://tools.ietf.org/html/rfc4918), particular as 207 is meant to be used when you are processing multiple resources and need to report different errors for the different resources being processed, and this is unlikely to be the case for a REST service.  

Moreover, the documentation implies that you should use 207 if you want to return additional information as an LCF exception XML payload, whereas there is no reason not to include such a payload with any other HTTP error response.

So we currently have multiple ways of representing the same error e.g. request denied could be

- HTTP Response 207 with EXC07 XML payload
- HTTP Response 403 with no payload
- HTTP Response 403 with EXC07 XML payload 

My recommendation would be that:

1. we drop HTTP Response Code 207 entirely.
2. we add text about including the LCF Exception XML as a payload to HTTP error responses
3. we make a decision whether that text should say that the XML Payload MAY, SHOULD or MUST be included in with a HTTP error response.

For reference, this is my mapping of EXC codes and HTTP Status codes. This might be worth including in the documentation (with any corrections):

| Exception condition code | HTTP response code |
| ------------------------- | --------------------- |
| EXC01                            | 503                           |
| EXC02                            | 401                           |
| EXC03                            | 401                           |
| EXC04                            | 500                           |
| EXC05                            | 404                           |
| EXC06                            | 422                           |
| EXC07                            | 403                           |
| EXC08                            | 404                           |
| EXC09                            | 404                           |

**Comment by franciscave** [comment]
I'd forgotten about this discussion, but it is coming back to me. The code list doesn't currently include an HTTP response code for EXC02, EXC05, EXC06, EXC07 or EXC09. '401' in the case of EXC02 makes obvious sense, and '404' in the case of EXC05. For EXC06 there seems to be a debate online about whether the response should be '400' or '422' - any thoughts? I'm not sure about returning a '404' with EXC09. Response code '507' seems appropriate, but is a WebDAV-specific response - some other '5xx' response maybe?

**Comment by franciscave** [comment]
Sorry, '403' with EXC07, I agree.

**Comment by franciscave** [comment]
I've removed reference to HTTP response code 207 from the Note under code list EXC. I have revised Implementation Note 5 of the LCF REST Web Service Specification as follows:

"In a RESTful web service implementation exception condition responses should generally be carried by an HTTP response status code. Where appropriate, in order to be more specific about the exception conditions that apply, an XML payload that conforms to the LCF Exception Conditions XML schema may be included in the response, if it is valid to include a payload with the specific HTTP response status code."

**Comment by franciscave** [comment]
I've removed reference to HTTP response code 207 from the Note under code list EXC. I have revised Implementation Note 5 of the LCF REST Web Service Specification as follows:

"In a RESTful web service implementation exception condition responses should generally be carried by an HTTP response status code. Where appropriate, in order to be more specific about the exception conditions that apply, an XML payload that conforms to the LCF Exception Conditions XML schema may be included in the response, if it is valid to include a payload with the specific HTTP response status code."

I've also made other minor adjustments to eliminate references to HTTP response code 207.
