### ISSUE TITLE
Authority ID

### ISSUE THREAD

**Issue by Neil-IMIL** [anthonywhitford/bic-lcf#68]
Some of the LMS multi-authority implementations return an authority ID via extensions to the current SIP2 response 64. This is used by authorities to implement different charging rates for different services based on the patron’s main authority. How best should this be replicated in the authentication or authorisation within LCF?

**Comment by mdovey** [comment]
See also #67 as specific use case scenario

**Comment by mdovey** [comment]
Can be addressed using new feature described in #55

**Comment by mdovey** [comment]
closed by accident

**Comment by franciscave** [comment]
I propose that a new Institution/authority entity be created with a structure roughly as follows:
- Institution/authority identifier (1)
- Alternative institution/authority identifier (0-n)
-- Identifier scheme (1)
-- Identifier scheme name (0-1)
-- Identifier value (1)
- Institution name (1)
- Related location (0-n)
-- Location relationship (1)
-- Location reference (1-n)
- Related contact (0-n)
-- Contact relationship (1)
-- Contact reference (1-n)
- Related institution/authority (0-n)
-- Institution/authority relationship (1)
-- Institution/authority reference (1-n)

**Comment by franciscave** [comment]
We could then add Associated institution/authority composites to the following entities:
- Item (e.g. to specify item owner, as a replacement for E02D05)
- Patron (e.g. to specify the patron's home institution, as a replacement for E03C03)
- Location
- Loan
- Reservation
- Charge
- Payment
- Contact
- Authorisation

**Comment by franciscave** [comment]
I have added this new entity (E14), with some minor revisions, to LCF v1.0.1 specification and entity XML binding. Please review.

**Comment by franciscave** [comment]
This was reviewed by the Technical Panel earlier today. It was generally agreed that there should be references in both directions where required between Item, Patron and Authority entities. I'm surprised if an Authority record needs to contain references to all the thousands of Patrons associated with that Authority, so I'd have expected the reference to be from Patron to Authority but not the other way around. However, I'll add the references in both directions for now.

It was agreed that a Contact could be required for a specific Location, e.g. the address, phone number or email of a specific library branch.

The Contact entity needs to be modified, because currently E09D03 Patron reference is mandatory. There should instead be a mandatory choice between Patron reference, Authority reference and Location reference, depending upon with what type of entity the Contact is associated.

**Comment by franciscave** [comment]
Changed the description of E02D05 Item owner in the LCF Version 1.0.1 specification. Consequentially, changed the tag name of E02D05 in the LCF v1.0.1 XML Binding from 'owner' to 'owner-ref', as it is now a reference to an Authority / Institution entity.

Added E03D34 Patron's home institution to LCF Version 1.0.1 specification (immediately preceding E03D04). Consequently added 'home-institution-ref' to the LCF v1.0.1 XML Binding for entity E03.

Added E14D08 Patron reference and E14D09 Item reference to LCF Version 1.0.1 specification. Consequently added 'patron-ref' and 'item-ref' to the LCF v1.0.1 XML Binding for entity E14.

Added E09D10 Location reference and E09D11 Authority/Institution reference to LCF Version 1.0.1 specification. Consequently added 'location-ref' and 'institution-ref' to the LCF v1.0.1 XML Binding for entity E09.

Added E04D07 Contact reference to LCF Version 1.0.1 specification. Consequently added 'contact-ref' to the LCF v1.0.1 XML Binding for entity E04.

**Comment by franciscave** [comment]
At today's Subgroup meeting it was agreed that I needed to correct the cardinality of E04D07 in the LCF V1.0.1 specification from '1' to '0-n' (it is correct in the XML binding). It was also agreed that E14D08 and E14D09 should be removed, because we could not see a practical use case for including long lists of Patron and Item references in Authority/Institution records.

**Comment by mdovey** [comment]
For the additional-authority-id is it deliberate that the subfields called id-type-name and id-value whereas for additional-item-id and additional-location-id, the corresponding fields are call type-name and value?

**Comment by mdovey** [comment]
Is there a reason why patron-ref, location-ref and institution-ref have cardinality 0-n rather than 0-1 (the original cardinality of patron-ref was 1-1 so I can see why this would change to 0-1 with the introduction of the addition location-ref and institution-ref but not why it changes to 0-n).

**Comment by franciscave** [comment]
The names 'id-type-name' and 'id-value' were my mistake. I was confusing naming conventions in LCF with naming conventions in other namespaces for which I am responsible. I have corrected the XML binding specification.

**Comment by franciscave** [comment]
The cardinality of patron-ref, location-ref and institution-ref in E09 should be 0-1 in each case. I've corrected the specifications. Also only one of these should be present in any instance of E09, so I've corrected the notes in the XML binding specification. I should probably make this clear in the LCF version 1.0.1 specification too...

**Comment by franciscave** [comment]
Clarified in the LCF version 1.0.1 specification, in the notes to E09D03.
