### ISSUE TITLE
Entity notes should be repeatable in all cases

### ISSUE THREAD

**Issue by franciscave** [anthonywhitford/bic-lcf#92]
The specification incorrectly has cardinality '0-1' for the following entity notes:
  -  E10C03 Scheme description note
  -  E11C05 Classification description note
  -  E13C04 Authorisation description / note
  -  E14C07 Authority/institution description / note

This isn't a serious error, as there is only one type of note defined at present and there can't sensibly be two notes of the same type. However, for consistency, this should be corrected, to allow for more than one type of note in future.

**Comment by mdovey** [comment]
The xml schema has these as repeatable, so it is probably best leaving them this way and updating the documentation - apart from Contact where note seems to be missing so that will need to be fixed.

Alert \ Message also doesn''t have a note field in either the documentation or xml schema. I suspect that this was deliberate as an Alert \ Message is a type of note. However, it is probably worth adding this too, as some (future) note types might be machine readable and as applicable to alert \ message as other entities

**Comment by franciscave** [comment]
OK, the element 'note' now has cardinality '0-n' on all entities, including E15 Message / alert.
